// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVBXanhabmU3cVRZWXhUUWZqQ29ySVFiUklYR1V2SVk2bHQ5T0tITE1sUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUXY4cG5aTFdkN0tDWnUvdTJDOG9MdzVYeGtrRWg2Z24vUkpmeXFuOTVSTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBTTgwTXpiTzhMZkRiMG1aTWJYdDhWYWNDcEVYNFc1QkFUam5GMkRjTUdBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhWEd2Y0FBZWZQVFhML2pUUWsyclFrOVY2STE5NHdqQkNGb25EUGVmT0ZFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtOTWc1ejQ2czhhaWNPbVhUV09aNWNJbGFlTGxTRzFjbXpWL3ZnSXIwV289In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlU0Sm9kYmZ4M3JkMW0xZjZ1ZnpqSVhQYTNtbnN2M2d5WkpBeHJQeHFNVUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUZ6T3VXaFRxb2ppekJ3dnE5K0tkSVk3TUwrNUtFQUp3TzNaY2E4TnRrOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUHNuc0FSTXB6TkRRVkt3ZHN2YkVZNWJvYitDMGQrS0FUQjlYOVd4aUExbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVCR1ppTk1HVndOWTBra3FOVURDZ1lrK09XcTFRTmlUYVVZSDUvU2NKckRMaS9KVUJFY09BTCs3YzdGWVRCdW8wejMwRDhXQ09nYU1HTXVDSC9iY0FnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTksImFkdlNlY3JldEtleSI6IlBqRWNDYk5waHVFRG5XS3ROQmc2dlZhWDlWK1MzU0Y2RVNqVzZwOWVoOE09IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6InhOaHlSc2ZrU3RDajlOc2M4UDN2OHciLCJwaG9uZUlkIjoiNGU3ZTFhZTQtMTQ5Yi00NTkyLWFlZjMtZGQ2YmE2YWYxYWY3IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndWTm5pbTBabDVTUFVEdGVwMTV4Z3JjQVBhWT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJMR2VkUnV6VHdsWmY0eEJ3WjZLODYwdjZLMGc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiN1Y4NVQ5WUYiLCJtZSI6eyJpZCI6IjIzNDkwMjEyODczODE6NDJAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0k3TWpMQUNFUEhmL2JjR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImlQeWdPVjRuSk1RVlI4Q3p4ZTF2b0xVWHVVcmJ6a3h2eTJoNGRoN2ZZZ0U9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImhVcGdCQS9odTVoYVpBeEhEODluYndWTXRKd2dTUGVOeHN6cTFqd1Nia1ZQbUJtaVBqeGp6VUdVd2g0UDk4enNWeTVRa2lhVmRuTUZYZmR4YXNON0N3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJva3lKSERocUlDWkdSY2lCeEJZZU1admVzbFA5eGlhNWRZMVIvZ1VJVkJxZ1ZjWjl4VGR5ZkZlT3ZPZTVwWHppRGhidXJFeUFySGF2c0x3NVBJNEdDQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDkwMjEyODczODE6NDJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWWo4b0RsZUp5VEVGVWZBczhYdGI2QzFGN2xLMjg1TWI4dG9lSFllMzJJQiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyODAxNjM4MywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFJbHgifQ==",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "GOJO",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "2349021287381",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
